version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:15
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env

  bmi:
    image: ${DOCKER_LOGIN}/bmi
    build: ./
    env_file: .env
    volumes:
      - static:/static
    depends_on:
      - db

  gateway:
    image: ${DOCKER_LOGIN}/bmi-gateway
    build: ./nginx/
    env_file: .env
    ports:
      - 80:80
    volumes:
      - static:/static
    depends_on:
      - db
      - bmi
