# Generated by Django 5.0.2 on 2024-03-03 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('canceled', 'canceled'), ('failed', 'failed'), ('succeeded', 'succeeded')], default='created', verbose_name='status'),
        ),
    ]
