# Generated by Django 5.0.2 on 2024-02-29 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='id')),
                ('type', models.CharField(choices=[('physical', 'physical'), ('services', 'services'), ('digital', 'digital')], max_length=50, verbose_name='type')),
                ('description', models.TextField(max_length=512, verbose_name='description')),
            ],
            options={
                'verbose_name': 'tax',
                'verbose_name_plural': 'taxes',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='modified')),
                ('name', models.CharField(max_length=128, verbose_name='name')),
                ('description', models.TextField(max_length=1024, verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='price')),
                ('currency', models.CharField(choices=[('usd', 'dollar'), ('eur', 'euro')], verbose_name='currency')),
                ('tax', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='items.tax', verbose_name='taxes')),
            ],
            options={
                'verbose_name': 'item',
                'verbose_name_plural': 'items',
                'ordering': ('name',),
            },
        ),
    ]
